name: "Terraform github action"

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '.github/**'

env:
  tf_version: '0.15.5'
  tf_working_dir: './setups'
  project: 'acg-etl'
  aws_region: 'us-east-2' 
  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #aws-region: us-east-1
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7] 
    
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
  terraform:
    name: 'Terraform'
    needs: build
    runs-on: ubuntu-latest
    env:
      project-home-directory: ./
    strategy:
      matrix:
        python-version: [3.7]
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false

      - name: 'Terraform Plan'
        id: plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false

      - name: 'Set up Python 3.x'
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.9'

      - name: 'Package Libraries'
        if: steps.plan.outputs.tf_actions_plan_has_changes == 'true'
        run: |
          python --version
          mkdir -p ~/cloud-resume/python/lib/python3.7/site-packages
          cd ~/cloud-resume/python/lib/python3.7/site-packages
          python3.7 -m pip install -r ~/cloudguru-resumechallenge-main/requirements.txt  -t .
          zip -r python.zip .
          mv python.zip ~/cloudguru-resumechallenge-main/setup/files_to_upload/
          ls -la ~/cloudguru-resumechallenge-main/setup/files_to_upload/
      
      - name: 'Package App'
        run: |
          cd ~/cloudguru-resumechallenge-main/
          zip -r counter.zip . -x ".*" "counter.py"
          mv counter.zip ./setup/files_to_upload/
          ls -la ./setup/files_to_upload/

      - name: 'Terraform Apply'
        if: steps.plan.outputs.tf_actions_plan_has_changes == 'true'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false
